# name: Dashboard CI

# on:
#   push:
#     branches:
#       - main
#       - working
#   pull_request:
#     branches:
#       - main
#       - working

# jobs:
#   build-lint:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 22
#           cache: npm
#           cache-dependency-path: package-lock.json

#       - name: Install dependencies
#         run: npm ci

#       - name: Build
#         run: npm run build

#       - name: Lint
#         run: npm run lint




name: Dashboard CI

on:
  push:
    branches:
      - main
      - working
  pull_request:
    branches:
      - main
      - working
  workflow_dispatch:

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint